---
- hosts: all

  tasks:
  - name: Fetch Java version
    become: true
    shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
    register: java_version

  - assert:
      that: 
        - java_version.stdout is version('1.9', '>=') 
